#!/bin/bash
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
hn=$(hostname -f)
fv=$(facter -j  --external-dir /opt/puppet-ml/lib/facts.d ipaddress macaddress architechture fqdn operatingsystem lsbdistdescription operatingsystemrelease boardmanufacturer productname serialnumber memorysize processorcount timezone uptime virtual hardwareisa swapsize swapfree memoryfree )
df="/tmp/facts.data"
cat <<EOF  >$df
{"facts":$fv,"name":"$hn","certname":"$hn"}
EOF
curl -H "Accept: */*, application/json,version=2" -H "Content-Type: application/json"  -X POST --data @$df http://foreman.example.com:3000/api/hosts/facts

