#!/bin/bash
# rsync get code and run it
#sleep ${1:-$(($RANDOM%30))}
export RSYNC_PASSWORD=youpasswd
export PATH="/bin:/usr/bin:/usr/sbin:/sbin"
WD="/opt/puppet-ml/instances/ins1"
FN="ins1-puppet.tar.xz.gpg"
mkdir -p $WD
[ ${#WD} -gt 20 ]&&rm ${WD}/* -rf


rsync --timeout=10 --contimeout=15 -avz --delete  puppet@www.example.com::newpuppet/${FN} /tmp/${FN}
gpg --verify  /tmp/${FN}&&gpg -d /tmp/${FN} |tar xf -  --lzma  -C ${WD}/
[ -d ${WD}/manifests ]&&puppet apply --config /opt/puppet-ml/etc/puppet.conf --modulepath=${WD}/modules ${WD}/manifests
exit 0

